### ISSUE TITLE
Option weights does not work

### ISSUE THREAD

**Issue by moritzdrechselgrau** [matthieugomez/Binscatters.jl#9]
The following MWE illustrates that using weights in the binscatter does not make a difference even though it clearly should.

```julia
using DataFrames, Binscatters, FixedEffectModels, Random

Random.seed!(1234)
n = 1000
df = DataFrame(x = 1:n, w = rand(n))
df.y = df.x .* (df.w .< 0.5)

r1 = reg(df, @formula(y ~ x)) # slope ≈ 0.50
r2 = reg(df, @formula(y ~ x); weights=:w) # slope ≈ 0.25

p1 = binscatter(df, @formula(y ~ x); seriestype=:linearfit)
p2 = binscatter(df, @formula(y ~ x); weights = :w, seriestype=:linearfit)
plot(p1, p2, size=(500,300)) # same plot
```

**Comment by matthieugomez** [comment]
Thanks, it should be corrected in the last commit https://github.com/matthieugomez/Binscatters.jl/commit/36bbc491ebc11c112fee10673b573e343552cacc. Could you check it out?

**Comment by moritzdrechselgrau** [comment]
I'm now getting this error. 
```julia
ERROR: MethodError: no method matching plot(::Binscatters.Binscatter)
Stacktrace:
 [1] binscatter(::DataFrame, ::Vararg{Any}; kwargs::@Kwargs{})
   @ Binscatters C:\Users\Drechsel-Grau\.julia\packages\Binscatters\x186K\src\Binscatters.jl:60     
 [2] top-level scope
   ... [path to my file]:11
```
Does the above MWE work on your machine?

**Comment by matthieugomez** [comment]
I think you need to add using Plots

**Comment by moritzdrechselgrau** [comment]
Great, it works. I didn't have to add Plots before, though. Is that intended?

**Comment by matthieugomez** [comment]
I'm pretty sure you always needed Plots

**Comment by moritzdrechselgrau** [comment]
You're right. I must not have killed julia before running the code above. My bad. Thanks for the quick fix!

**Comment by matthieugomez** [comment]
no problem, thanks for the report, it was a pretty big issue!
